# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
workspace 'Bugbattle'

target 'Bugbattle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BugBattle
  pod 'BugBattle'
end
